### ISSUE TITLE
How do I remove the error messages ?

### ISSUE THREAD

**Issue by AngeloMerlo** [victorjonsson/jQuery-Form-Validator#227]
I want to make only the edge of another color but without displaying messages.

ty

**Comment by victorjonsson** [comment]
The simplest way to remove the error messages is to hide them with css.

```css
.help-block.form-error {
   display:none;
}
```
